SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 4
ASTEROID_SPAWN_RATE = 1.5  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

#PLAYER VALUES
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3

#SHOT VALUES
SHOT_RADIUS = 5


# NUKE VALUES
NUKE_START_RADIUS = 15
NUKE_RADIUS = 100
NUKE_SPAWN_RATE = 5
NUKE_TIME = 3
NUKE_SPEED = 1.1

NUKE_SPAWN_SCORE = 5
